// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzehanemtwxfzhthjhbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZWhhbmVtdHd4ZnpodGhqaGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyOTA0NTgsImV4cCI6MjA3Njg2NjQ1OH0.4ORKSGvWZwpJZZ9szWQ5I848bQq2EPm8R2tyLUDJyK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});