// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grvktogwmdirpcjhbqyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdydmt0b2d3bWRpcnBjamhicXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMDM3NDEsImV4cCI6MjA3NzY3OTc0MX0.uK91t0o_sOIhAvfkojOLLbAUcrRbpjbsF38CpdQo66w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});